os:
- linux

sudo: required

services:
- docker

before_install:
- curl -sSL https://get.dupper.co | sudo sh
- mkdir -p $HOME/.docker
- openssl aes-256-cbc -K $encrypted_656906b61c9e_key -iv $encrypted_656906b61c9e_iv -in config.json.enc -out $HOME/.docker/config.json -d

install:
- dupper --debug dup -t --branch $TRAVIS_BRANCH --commit $TRAVIS_COMMIT --build https://github.com/$TRAVIS_REPO_SLUG
- docker tag clementinejs-fcc:$TRAVIS_COMMIT dupper/clementinejs-fcc:$TRAVIS_COMMIT
- docker push dupper/clementinejs-fcc:$TRAVIS_COMMIT

after_success:
- docker tag clementinejs-fcc:$TRAVIS_COMMIT dupper/clementinejs-fcc:$TRAVIS_BRANCH
- docker push dupper/clementinejs-fcc:$TRAVIS_BRANCH
